// apps/app-vue/src/components/Modal.vue
<script setup lang="ts">
import { onUnmounted } from "vue";

const { onDestroyModal } = defineProps<{
  title: string;
  onDestroyModal?: () => void;
}>();

onUnmounted(() => {
  onDestroyModal?.();
});
</script>

<template>
  <div class="modal">
    <div class="modal-backdrop"></div>
    <div class="modal-content">
      <!-- Modal header -->
      <div class="modal-header">
        <h3 class="modal-title">{{ title }}</h3>
      </div>
      <!-- Modal body -->
      <div class="modal-body">
        <slot name="body" />
      </div>
      <!-- Modal footer -->
      <div class="modal-footer">
        <slot name="footer" />
      </div>
    </div>
  </div>
</template>

// apps/app-svelte/src/lib/components/Modal.svelte
<script lang="ts">
  import { onDestroy } from "svelte";

  export let title: string;
  export let onDestroyModal: (() => void) | null = null;

  onDestroy(() => {
    onDestroyModal?.();
  });
</script>

<div class="modal">
  <div class="modal-backdrop"></div>
  <div class="modal-content">
    <!-- Modal header -->
    <div class="modal-header">
      <h3 class="modal-title">{title}</h3>
    </div>
    <!-- Modal body -->
    <div class="modal-body">
      <slot name="body" />
    </div>
    <!-- Modal footer -->
    <div class="modal-footer">
      <slot name="footer" />
    </div>
  </div>
</div>
