// apps/app-svelte/src/lib/components/FormInput.svelte
<script lang="ts">
  export let id: string | null = null;
  export let title: string = "";
  export let inputType: "text" | "date" = "text";
  export let value: string;
  export const focus = () => {
    inputRef.focus();
  };

  let inputRef: HTMLInputElement;
</script>

<div class="form-group">
  {#if title && id}
    <label for={id} class="form-label">{title}</label>
  {/if}

  {#if inputType == "date"}
    <input
      {id}
      type="date"
      class="form-input"
      bind:this={inputRef}
      bind:value
    />
  {:else}
    <input {id} class="form-input" bind:this={inputRef} bind:value />
  {/if}
</div>

// apps/app-vue/src/components/FormInput.vue
<script setup lang="ts">
import { ref } from "vue";

defineProps<{
  id?: string;
  title?: string;
  inputType?: "text" | "date";
}>();

const value = defineModel<string>("value");

const inputRef = ref<HTMLInputElement | null>(null);

const focus = () => {
  inputRef.value?.focus();
};

defineExpose({
  focus,
});
</script>

<template>
  <div class="form-group">
    <label v-if="title && id" :for="id" class="form-label">{{ title }}</label>
    <input
      :id="id"
      :type="inputType"
      class="form-input"
      ref="inputRef"
      v-model="value"
    />
  </div>
</template>
